/**
 * LES CARTES DES MODULES PROPRES À L'INTERNE (Bloc 3).
 *
 * Ce que ça fait, pour qui, un exemple — pour les modules que seule l'édition
 * interne embarque (Tour de contrôle, Parc, Produits, Livrables). Elles vivent
 * ici et non dans les dictionnaires communs, parce que le bundle Business ne
 * doit porter aucune trace de ces produits ni d'AMN DevSec : le garde
 * check-business-bundle l'a refusé, à raison, à la première tentative.
 *
 * Clés : `<module>.quoi` / `.pourQui` / `.exemple`, lues par `carteModule`.
 */
export const CARTES_INTERNES_FR: Record<string, string> = {
  'gardeSalle.quoi': 'Le mur des gardes : chaque équipe, chaque agent, ce qu’il fait maintenant, ce qu’il a trouvé.',
  'gardeSalle.pourQui': 'AMN DevSec — pour voir que quelqu’un veille.',
  'gardeSalle.exemple': '« Disponibilité · en ronde : les sites joignables de l’extérieur. »',
  'gardePile.quoi': 'Une seule pile de ce qui attend une décision humaine, triée par gravité, avec le contexte et une recommandation.',
  'gardePile.pourQui': 'Aaron et Mohamed.',
  'gardePile.exemple': '« Le certificat de jardin.fr expire dans trois jours — prévenir la cliente ? »',
  'gardeBureaux.quoi': 'Le bureau de chaque chef de garde : on lui pose des questions, il répond avec ses preuves, on lui donne des ordres.',
  'gardeBureaux.pourQui': 'AMN DevSec.',
  'gardeBureaux.exemple': '« Qu’as-tu fait cette nuit ? » — « Trois points réglés sans vous, une remontée. »',
  'gardeCommune.quoi': 'Parler à toute la Garde d’un coup : une consigne, une absence, et la Relève du jour.',
  'gardeCommune.pourQui': 'Aaron, avant de partir et en revenant.',
  'gardeCommune.exemple': '« On va s’absenter un petit temps. » — chaque chef répond en une ligne.',
  'gardeCalendrier.quoi': 'Ce que la Garde fera cette semaine : rondes, rapports, fins de grâce, la Relève. Aucune surprise.',
  'gardeCalendrier.pourQui': 'AMN DevSec.',
  'gardeCalendrier.exemple': '« Lundi 8 h — tour des bureaux. Mardi — fin de grâce de NWSY. »',
  'team.quoi': 'L’équipe interne : qui fait quoi, qui est joignable.',
  'team.pourQui': 'AMN DevSec.',
  'team.exemple': '« Mohamed — supervision — en ligne. »',
  'decisions.quoi': 'Les décisions prises, datées, avec leur raison.',
  'decisions.pourQui': 'AMN DevSec.',
  'decisions.exemple': '« 2 sept. : Postgres sur Render, pas SQLite — raison : sauvegardes. »',
  'knowledge.quoi': 'Ce qu’on sait et qu’on ne veut pas réapprendre.',
  'knowledge.pourQui': 'AMN DevSec.',
  'knowledge.exemple': '« Procédure : réémettre un accès à une cliente. »',
  'library.quoi': 'Tous les modules, rangés, et leur état.',
  'library.pourQui': 'AMN DevSec.',
  'library.exemple': '« 85 modules, 68 ouverts aux clientes. »',
  'tour.quoi': 'Le parc en une page : organisations, activité, files.',
  'tour.pourQui': 'Aaron, en arrivant.',
  'tour.exemple': '« 27 organisations, 3 demandes à traiter. »',
  'orgs.quoi': 'Chaque organisation cliente, son dossier, ses gestes.',
  'orgs.pourQui': 'Aaron.',
  'orgs.exemple': '« Fleuriste d Essai : formule Standard, 2 places, ouvrir le dossier. »',
  'access.quoi': 'Chaque geste d’AMN DevSec chez une cliente, lisible.',
  'access.pourQui': 'Aaron, et la cliente dans ses réglages.',
  'access.exemple': '« Aaron a ouvert un module chez Atelier London — Messages privés, ajouté hors formule. »',
  'generator.quoi': 'Créer une organisation cliente en quelques minutes.',
  'generator.pourQui': 'Aaron.',
  'generator.exemple': '« Nouvelle boutique, formule Standard, langue anglaise. »',
  'supervision.quoi': 'Les incidents du parc : prendre, résoudre, étouffer, planifier une maintenance.',
  'supervision.pourQui': 'Qui tient le SOC.',
  'supervision.exemple': '« Critique non pris depuis 12 min sur site-3 : escaladé. »',
  'sites.quoi': 'Les sites surveillés et leur état.',
  'sites.pourQui': 'Qui tient le SOC.',
  'sites.exemple': '« 24 sites, 2 hors ligne. »',
  'tracker.quoi': 'Ce que le traceur voit sur chaque site, en direct.',
  'tracker.pourQui': 'Qui tient le SOC.',
  'tracker.exemple': '« 41 visiteurs actifs, 1 tentative d’injection bloquée. »',
  'socMaturity.quoi': 'Six signaux par cliente : où en est sa sécurité.',
  'socMaturity.pourQui': 'Aaron, pour parler à une cliente.',
  'socMaturity.exemple': '« Atelier London : MFA activée, sauvegardes non vérifiées. »',
  'orgCompare.quoi': 'Les clientes côte à côte : activité, modules, incidents.',
  'orgCompare.pourQui': 'Aaron.',
  'orgCompare.exemple': '« Qui n’a rien écrit depuis 30 jours ? »',
  'customAlerts.quoi': 'Vos propres règles d’alerte sur le parc.',
  'customAlerts.pourQui': 'Aaron.',
  'customAlerts.exemple': '« Si une cliente est muette 14 jours, préviens-moi. »',
  'clientReport.quoi': 'Un rapport mensuel par cliente, prêt à envoyer.',
  'clientReport.pourQui': 'Aaron.',
  'clientReport.exemple': '« Rapport d’août pour Fleuriste : 190 enregistrements, 0 incident. »',
  'scanner.quoi': 'Un site passé au crible : en-têtes, fichiers exposés, DNS.',
  'scanner.pourQui': 'Qui audite un site.',
  'scanner.exemple': '« exemple.fr : 3 en-têtes manquants, .git exposé. »',
  'comply.quoi': 'Les référentiels de conformité, vérifiés point par point.',
  'comply.pourQui': 'Qui accompagne une cliente sur la conformité.',
  'comply.exemple': '« RGPD : 12 points sur 18 en place. »',
  'ssl.quoi': 'Les certificats, leur expiration, leurs faiblesses.',
  'ssl.pourQui': 'Qui tient le SOC.',
  'ssl.exemple': '« exemple.fr : expire dans 9 jours. »',
};

export const CARTES_INTERNES_EN: Record<string, string> = {
  'gardeSalle.quoi': 'The wall of guards: every team, every agent, what it is doing now, what it found.',
  'gardeSalle.pourQui': 'AMN DevSec, to see that someone is watching.',
  'gardeSalle.exemple': '“Availability · on patrol: sites reachable from outside.”',
  'gardePile.quoi': 'One pile of what awaits a human decision, sorted by severity, with context and a recommendation.',
  'gardePile.pourQui': 'Aaron and Mohamed.',
  'gardePile.exemple': '“The certificate of jardin.fr expires in three days: warn the client?”',
  'gardeBureaux.quoi': 'Each guard chief’s office: ask questions, get answers with proof, give orders.',
  'gardeBureaux.pourQui': 'AMN DevSec.',
  'gardeBureaux.exemple': '“What did you do tonight?” — “Three points settled without you, one escalated.”',
  'gardeCommune.quoi': 'Talk to the whole Guard at once: an instruction, an absence, and the daily brief.',
  'gardeCommune.pourQui': 'Aaron, before leaving and when back.',
  'gardeCommune.exemple': '“We will be away for a while.” — every chief answers in one line.',
  'gardeCalendrier.quoi': 'What the Guard will do this week: patrols, reports, grace deadlines, the brief. No surprises.',
  'gardeCalendrier.pourQui': 'AMN DevSec.',
  'gardeCalendrier.exemple': '“Monday 8 am: office tour. Tuesday: NWSY grace ends.”',
  'team.quoi': 'The internal team: who does what, who is reachable.',
  'team.pourQui': 'AMN DevSec.',
  'team.exemple': '“Mohamed — supervision — online.”',
  'decisions.quoi': 'Decisions taken, dated, with their reason.',
  'decisions.pourQui': 'AMN DevSec.',
  'decisions.exemple': '“2 Sept: Postgres on Render, not SQLite — reason: backups.”',
  'knowledge.quoi': 'What we know and do not want to relearn.',
  'knowledge.pourQui': 'AMN DevSec.',
  'knowledge.exemple': '“Procedure: reissue access to a client.”',
  'library.quoi': 'Every module, sorted, and its state.',
  'library.pourQui': 'AMN DevSec.',
  'library.exemple': '“85 modules, 68 open to clients.”',
  'tour.quoi': 'The fleet on one page: organisations, activity, queues.',
  'tour.pourQui': 'Aaron, on arrival.',
  'tour.exemple': '“27 organisations, 3 requests to handle.”',
  'orgs.quoi': 'Every client organisation, its dossier, its gestures.',
  'orgs.pourQui': 'Aaron.',
  'orgs.exemple': '“Fleuriste d Essai: Standard plan, 2 seats, open the dossier.”',
  'access.quoi': 'Every AMN DevSec action at a client’s, readable.',
  'access.pourQui': 'Aaron, and the client in her settings.',
  'access.exemple': '“Aaron opened a module at Atelier London — Direct messages, added outside the formula.”',
  'generator.quoi': 'Create a client organisation in a few minutes.',
  'generator.pourQui': 'Aaron.',
  'generator.exemple': '“New shop, Standard plan, English.”',
  'supervision.quoi': 'The fleet’s incidents: take, resolve, suppress, plan maintenance.',
  'supervision.pourQui': 'Whoever runs the SOC.',
  'supervision.exemple': '“Critical unacknowledged for 12 min on site-3: escalated.”',
  'sites.quoi': 'Monitored sites and their state.',
  'sites.pourQui': 'Whoever runs the SOC.',
  'sites.exemple': '“24 sites, 2 offline.”',
  'tracker.quoi': 'What the tracker sees on each site, live.',
  'tracker.pourQui': 'Whoever runs the SOC.',
  'tracker.exemple': '“41 active visitors, 1 injection attempt blocked.”',
  'socMaturity.quoi': 'Six signals per client: where their security stands.',
  'socMaturity.pourQui': 'Aaron, to talk to a client.',
  'socMaturity.exemple': '“Atelier London: MFA on, backups unverified.”',
  'orgCompare.quoi': 'Clients side by side: activity, modules, incidents.',
  'orgCompare.pourQui': 'Aaron.',
  'orgCompare.exemple': '“Who has written nothing for 30 days?”',
  'customAlerts.quoi': 'Your own alert rules on the fleet.',
  'customAlerts.pourQui': 'Aaron.',
  'customAlerts.exemple': '“If a client is silent for 14 days, tell me.”',
  'clientReport.quoi': 'A monthly report per client, ready to send.',
  'clientReport.pourQui': 'Aaron.',
  'clientReport.exemple': '“August report for Fleuriste: 190 records, 0 incident.”',
  'scanner.quoi': 'A site put through the sieve: headers, exposed files, DNS.',
  'scanner.pourQui': 'Anyone auditing a site.',
  'scanner.exemple': '“example.fr: 3 headers missing, .git exposed.”',
  'comply.quoi': 'Compliance frameworks, checked point by point.',
  'comply.pourQui': 'Anyone guiding a client on compliance.',
  'comply.exemple': '“GDPR: 12 points out of 18 in place.”',
  'ssl.quoi': 'Certificates, their expiry, their weaknesses.',
  'ssl.pourQui': 'Whoever runs the SOC.',
  'ssl.exemple': '“example.fr: expires in 9 days.”',
};
